sudo: required
language: go
go_import_path: golang.org/x/build

services:
  - docker

go:
  - 1.8
  - tip

script:
  - go vet ./... || true
  - go test -v -race ./...
  - pushd cmd/coordinator && make docker-dev && popd
  - pushd cmd/gitmirror && make docker-dev && popd
